//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPr5.DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class artEstraviados
    {
        [DataMember] public int idArticuloExt { get; set; }
        [DataMember] public string nombre { get; set; }
        [DataMember] public Nullable<int> idCategoria { get; set; }
        [DataMember] public Nullable<System.DateTime> FechaIngreso { get; set; }
        [DataMember] public string descripcion { get; set; }
        [DataMember] public string IngresadoPor { get; set; }
        [DataMember] public Nullable<int> Telefono_Contacto { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
