//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPr5.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoPR5Entities : DbContext
    {
        public ProyectoPR5Entities()
            : base("name=ProyectoPR5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<artCustodia> artCustodia { get; set; }
        public virtual DbSet<artEntregados> artEntregados { get; set; }
        public virtual DbSet<artEstraviados> artEstraviados { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
    }
}
