//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPr5.DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class Usuarios
    {
        [DataMember] public int idUsuario { get; set; }
        [DataMember] public string cedula { get; set; }
        [DataMember] public string pass { get; set; }
        [DataMember] public Nullable<int> idRol { get; set; }
        [DataMember] public string nombre { get; set; }
        [DataMember] public Nullable<int> telefono { get; set; }
        [DataMember] public string correo { get; set; }
    }
}
